# Generated by Django 5.2.1 on 2025-06-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipogasto_remove_doctor_duracion_cita_and_more'),
        ('doctor', '0005_remove_atencion_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='horarios_atencion',
            field=models.ManyToManyField(blank=True, help_text='Horarios predefinidos seleccionables', related_name='doctores', to='doctor.horarioatencion', verbose_name='Horarios de Atención'),
        ),
    ]
