# Generated by Django 5.2.1 on 2025-07-03 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doctor_horarios_atencion'),
        ('doctor', '0005_remove_atencion_doctor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citamedica',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='citas_medicas', to='core.doctor', verbose_name='Doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('atendido', 'Atendido')], default='disponible', max_length=10, verbose_name='Estado de la Cita'),
        ),
        migrations.AlterUniqueTogether(
            name='citamedica',
            unique_together={('doctor', 'fecha', 'hora_cita')},
        ),
    ]
